name: Print Github Context

on: workflow_dispatch

jobs:
    get-context:
        runs-on: ubuntu-latest
        steps:
            - name: Output Context
              run: echo "${{ toJson(github) }}"